version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: 'banking-api-rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - banking-api-net
networks:
  banking-api-net:
